name: tapify_admin
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5

  #--- State Management & Routing ---
  get: ^4.6.5

  #--- For Easy Logs ---
  logger: ^1.4.0

  #--- For Responsive Design ---
  flutter_screenutil: ^5.7.0

  #--- For SVG Assets Rendering ---
  flutter_svg:

  #--- For Showing Animated Marquee Text ---
  marquee: ^2.2.3

  #--- For Showing Products Carousels ---
  carousel_slider: ^4.2.1

  #---- For Showing Videos ---///
  video_player: ^2.7.0
  flick_video_player: ^0.5.0
  chewie: ^1.5.0
  flutter_xlider: ^3.5.0

  #---- For Setting Date & Times ---///
  intl: ^0.17.0

  #---- For Rating ------///
  flutter_rating_bar: ^4.0.1

  #------ For Customized Dropdowns -------
  dropdown_button2: ^1.8.2

  #------- For Custom Drawer Design
  flutter_advanced_drawer: ^1.3.5

  #-----bottom sheet-----
  sliding_up_panel: ^2.0.0+1

  #------ Dio - For API Services ------
  dio: ^5.1.2

  #------ For Saving Data Locally ------
  get_storage: ^2.1.1
  timezone: ^0.8.0

  #------- Facebook App Events
  #  facebook_app_events: ^0.19.0

  #------- Shopify Storefront APIs
  #  shopify_flutter: ^1.0.8

  #------- For Showing Network Images
  cached_network_image: ^3.2.3

  #------- Flutter HTML -------
  flutter_html:

  #-----vibrate-----
  vibration: ^1.7.7

  #----- WebView for Checkout-----
  webview_flutter: ^4.2.2

  #----- shimmer ----
  shimmer: ^3.0.0

  #----- Pull to Refresh for Re Calling
  pull_to_refresh: ^2.0.0

  #----timelines----
  timelines: ^0.1.0
  flutter_spinkit: ^5.2.0
  photo_view: ^0.14.0

  share_plus: ^6.2.0

  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.4
  transparent_image: ^2.0.1

  graphql_flutter: ^5.1.2
  freezed_annotation: ^2.2.0
  json_serializable: ^6.6.1
  shared_preferences: ^2.0.20
  url_launcher: ^6.1.10
  loading_animation_widget: ^1.2.0+4
  animate_do: ^3.0.2
  flutter_slidable: ^3.0.0
  connectivity_plus: ^4.0.2
  flutter_barcode_scanner: ^2.0.0

  #-------local Notification-----
  flutter_local_notifications: ^9.4.0

  firebase_analytics: ^10.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  pedantic: ^1.11.1


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/icons/dynamic icons/

  fonts:
    - family: Sofia Pro Regular
      fonts:
        - asset: assets/fonts/Sofia Pro Regular.otf

    - family: Sofia Pro Medium
      fonts:
        - asset: assets/fonts/Sofia Pro Medium.otf

    - family: Sofia Pro Semi Bold
      fonts:
        - asset: assets/fonts/Sofia Pro Semi Bold.otf

